# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-22 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='end_time',
            field=models.TimeField(auto_now_add=True, default='00:00:PM'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='start_time',
            field=models.TimeField(auto_now_add=True, default='00:00:PM'),
            preserve_default=False,
        ),
    ]
